### ISSUE TITLE
ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION

### ISSUE THREAD

**Issue by mghabdo** [RocketChat/Rocket.Chat.Electron#1055]
**ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION**

`[11:35:19] 'release' errored after 37 s
[11:35:19] Error in plugin "run-sequence(release:win32)"
Message:
    Cannot find suitable Parallels Desktop virtual machine (Windows 10 is required)
Details:
    code: ERR_ELECTRON_BUILDER_INVALID_CONFIGURATION

Stack:
Error: Cannot find suitable Parallels Desktop virtual machine (Windows 10 is required)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/vm/vm.ts:25:9
From previous event:
    at _getWindowsVm (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/out/vm/vm.js:77:24)
    at getWindowsVm (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/out/vm/vm.js:65:24)
    at Lazy.WinPackager.vm (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/winPackager.ts:81:109)
    at Lazy.get value [as value] (/Users/mac/unicoorp/Knowative-Desktop/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/targets/AppxTarget.ts:48:34
From previous event:
    at AppXTarget.build (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/targets/AppxTarget.ts:37:44)
    at Function.buildAsyncTargets (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at WinPackager.packageInDistributableFormat (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at WinPackager.pack (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/mac/unicoorp/Knowative-Desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at Packager.doBuild (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
From previous event:
    at Packager._build (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Packager.build (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/mac/unicoorp/Knowative-Desktop/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/mac/unicoorp/Knowative-Desktop/node_modules/electron-builder/src/builder.ts:227:10)
    at Gulp.gulp.task (/Users/mac/unicoorp/Knowative-Desktop/tasks/release.js:11:34)
    at module.exports (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/mac/unicoorp/Knowative-Desktop/node_modules/run-sequence/index.js:124:15)
    at Gulp.onTaskEnd (/Users/mac/unicoorp/Knowative-Desktop/node_modules/run-sequence/index.js:102:4)
    at Gulp.emit (events.js:194:15)
    at Gulp.EventEmitter.emit (domain.js:441:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:264:8)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:214:10)
    at /Users/mac/unicoorp/Knowative-Desktop/node_modules/orchestrator/index.js:279:18
  • building block map blockMapFile=dist/rocketchat-setup-2.15.0-develop.exe.blockmap
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I' trying to make a release for windows , i'm using MacOs
node -v
v11.4.0
npm -v
6.5.0
i already have a VM Windows 10 on parallels Desktop

> Cannot find suitable Parallels Desktop virtual machine (Windows 10 is required)

**Comment by tassoevan** [comment]
@mghabdo Have you tried to look for a resolution on `electron-builder` repo (https://github.com/electron-userland/electron-builder)? We don't do cross-platform builds, so I don't know if it's supported.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
