### ISSUE TITLE
Crash if update check cannot contact GitHub server (2.15.1 regression)

### ISSUE THREAD

**Issue by nicoroeser** [RocketChat/Rocket.Chat.Electron#1152]
## My Setup
- Operating System: macOS
- Failing App Version: 2.15.1
- Working App Version: 2.15.0
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
If (and only if) “Check for Updates on Start” is checked in the “About Rocket.Chat” dialog and Rocket.Chat is started, and it cannot connect to the update server (GitHub releases server, which means Amazon Web Services for from where I connect), then the application can not start (it crashes, but the user does not see/understand that from the GUI; it seems that the application just does not start).

### Current Behavior
Software crashes due to an Error. After the message `Checking for update`, the following is output:
<pre>
Checking for update
Error: Error: net::ERR_ADDRESS_UNREACHABLE
    at GitHubProvider.getLatestVersion (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at checkForUpdates (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/src/background/updates.js:80:15)
    at EventEmitter.electron.ipcMain.on.args (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/src/background/updates.js:171:49)
    at EventEmitter.emit (events.js:182:13)
    at startApp (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/src/background.js:85:10)
Error: net::ERR_ADDRESS_UNREACHABLE
    at GitHubProvider.getLatestVersion (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at checkForUpdates (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/src/background/updates.js:80:15)
    at EventEmitter.electron.ipcMain.on.args (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/src/background/updates.js:171:49)
    at EventEmitter.emit (events.js:182:13)
    at startApp (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/src/background.js:85:10)
</pre>

### Expected Behavior
Failure to contact the update server is ignored as in version 2.15.0. User MAY be notified about the failure by a small, non-intrusive message (in a status bar or whatever; that does not require to be clicked away). Software MUST NOT crash.

**Comment by nicoroeser** [comment]
I can confirm that this issue has been fixed in 2.15.2. The exception is still thrown (which is normal) and is printed on the console (which is good). The application does not crash anymore.

Thanks!
