### ISSUE TITLE
Rocket.Chat dialog.about.errorWhileLookingForUpdates when checking for updates

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.Electron#1500]
## My Setup
- Operating System: macOS 10.15.3
- App Version: 2.17.3 + 2.17.5
- Installation type: dmg

- I have tested with the latest version (trying to update to latest version, so...)
- I can simulate the issue easily

## Description
![screenshot](https://user-images.githubusercontent.com/5708172/73774494-5c6b1c00-4784-11ea-83a1-1ebd30340bf7.png)

![screenshot2](https://user-images.githubusercontent.com/5708172/73774831-faf77d00-4784-11ea-917c-8dfd7140aff1.png)

### Current Behavior
dialog.about.errorWhileLookingForUpdates

### Expected Behavior
Should offer 2.17.5 update

**Comment by ankar84** [comment]
Windows versions 2.17.3-2.17.5 has that same bug too.

**Comment by cdisabatino** [comment]
Same problem with version 2.17.3 on Windows. I tested with two network connections, Wifi and RJ54. Without proxy.

**Comment by foss-** [comment]
For what it's worth update to 2.17.7 did show and execute as expected.Closing.

**Comment by ankar84** [comment]
I don't know, but 2.17.7 show me the same error
![image](https://user-images.githubusercontent.com/4023037/74302115-5b2e8600-4d66-11ea-8f46-71cf48facc6e.png)
` [bugsnag] Loaded!
Checking for update
Error: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"Headers: {
  "date": "Wed, 12 Feb 2020 04:03:38 GMT",
  "content-type": "text/plain; charset=utf-8",
  "transfer-encoding": "chunked",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept",
  "cache-control": "no-cache",
  "set-cookie": [
    "_gh_sess=OW9JN01OOGNiU0VVTUp0NUtzU1pZcVVkUzJHRXRoRXFES0Z0YlFheXJiaWpMUE9EVHpSa2MveU9mNU5EdDI3ZHlkSXBwMFRGV1FMYlBZSHk1aVczdnRJd0sxWDNTR2ppbHJ2QjZ2bG9abWhpMVFyWStMSFBFdDF1YnhtSWN0R09IUTlUT243Wml3VmRzOVRkb09yT3V1Y1JNalJZUURVdzdCTlZWem9PM2xCWmdjYjU2Nm96WnV1WW84dGxHTWhVZFRxYjRFbmg3Um5MemlkajVzeWV4L3FnK3c5bE1tMEVrSDc2cmlUR3R4R0FkbDRPQU1sRmUzbCtiSWVIRWRvKy0ta3pQQ1NNM0l1OXBsMG1QeFNBSHpRdz09--c2af9936bc7111955229d066e0f18a26bdd9be0a; path=/; secure; HttpOnly"
  ],
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "x-github-request-id": "E572:1C881:15979C:21E89E:5E43791A"
}
    at createHttpError (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
    at newError (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at GitHubProvider.getLatestVersion (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\out\providers\GitHubProvider.js:134:50)
Error: Cannot find latest.yml in the latest release artifacts (https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"Headers: {
  "date": "Wed, 12 Feb 2020 04:03:38 GMT",
  "content-type": "text/plain; charset=utf-8",
  "transfer-encoding": "chunked",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept",
  "cache-control": "no-cache",
  "set-cookie": [
    "_gh_sess=OW9JN01OOGNiU0VVTUp0NUtzU1pZcVVkUzJHRXRoRXFES0Z0YlFheXJiaWpMUE9EVHpSa2MveU9mNU5EdDI3ZHlkSXBwMFRGV1FMYlBZSHk1aVczdnRJd0sxWDNTR2ppbHJ2QjZ2bG9abWhpMVFyWStMSFBFdDF1YnhtSWN0R09IUTlUT243Wml3VmRzOVRkb09yT3V1Y1JNalJZUURVdzdCTlZWem9PM2xCWmdjYjU2Nm96WnV1WW84dGxHTWhVZFRxYjRFbmg3Um5MemlkajVzeWV4L3FnK3c5bE1tMEVrSDc2cmlUR3R4R0FkbDRPQU1sRmUzbCtiSWVIRWRvKy0ta3pQQ1NNM0l1OXBsMG1QeFNBSHpRdz09--c2af9936bc7111955229d066e0f18a26bdd9be0a; path=/; secure; HttpOnly"
  ],
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "x-github-request-id": "E572:1C881:15979C:21E89E:5E43791A"
}
    at createHttpError (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
Checking for update
Error: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Wed, 12 Feb 2020 04:05:54 GMT",
  "content-type": "text/plain; charset=utf-8",
  "transfer-encoding": "chunked",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept",
  "cache-control": "no-cache",
  "set-cookie": [
    "_gh_sess=NVdIZjIwa2d5WExvVkNyTGdqdXI4QkpnNlRrNGF3bGlLbENETGFJY1ZTT1M3SEFNRldpTXBERm5YYjcwR1dFMGNENmY2MC9IREhUMUsvb0Z0MGVOUHVRVHNCcTcvMVRqcTBncDFka29JYVpvb3J3L1FMaVltV2JSQ2plVWZWbkREOVgvMUtQNnFBSit1bVA3OWtJRHMvNXlTNC95QlNFeXRCNjZSSjFvSEhJbVVJK2N6M1BVQTJaM3Mvb2o0WkdSR2hDdVFFdmszY2h6QmdsR2JML0dyand5eFMzYzREbmhjSDFpQjlKeFBlTGJkVmIvbUNEWi9sNnp0cTVSTUF5Uy0tQmdLdnU1WVJZUzZTMlY0Rk5OZm5Udz09--80db9956156b9e9e1dcbcb97716084040265d69b; path=/; secure; HttpOnly"
  ],
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "x-github-request-id": "E58E:4020E:11E7F8:1C4010:5E4379A2"
}
    at createHttpError (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
    at newError (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\index.js:212:17)
    at GitHubProvider.getLatestVersion (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\out\providers\GitHubProvider.js:134:50)
Error: Cannot find latest.yml in the latest release artifacts (https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.7/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Wed, 12 Feb 2020 04:05:54 GMT",
  "content-type": "text/plain; charset=utf-8",
  "transfer-encoding": "chunked",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept",
  "cache-control": "no-cache",
  "set-cookie": [
    "_gh_sess=NVdIZjIwa2d5WExvVkNyTGdqdXI4QkpnNlRrNGF3bGlLbENETGFJY1ZTT1M3SEFNRldpTXBERm5YYjcwR1dFMGNENmY2MC9IREhUMUsvb0Z0MGVOUHVRVHNCcTcvMVRqcTBncDFka29JYVpvb3J3L1FMaVltV2JSQ2plVWZWbkREOVgvMUtQNnFBSit1bVA3OWtJRHMvNXlTNC95QlNFeXRCNjZSSjFvSEhJbVVJK2N6M1BVQTJaM3Mvb2o0WkdSR2hDdVFFdmszY2h6QmdsR2JML0dyand5eFMzYzREbmhjSDFpQjlKeFBlTGJkVmIvbUNEWi9sNnp0cTVSTUF5Uy0tQmdLdnU1WVJZUzZTMlY0Rk5OZm5Udz09--80db9956156b9e9e1dcbcb97716084040265d69b; path=/; secure; HttpOnly"
  ],
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "x-github-request-id": "E58E:4020E:11E7F8:1C4010:5E4379A2"
}
    at createHttpError (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (c:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
`

**Comment by cdisabatino** [comment]
For me, same error with version 2.17.7.

**Comment by foss-** [comment]
Re-opening as issue is persisting on Windows OS.

**Comment by rmaksimov** [comment]
The same with 2.17.8, 2.17.9

![rocket-chat-before](https://user-images.githubusercontent.com/2904679/76658618-900c4380-6585-11ea-98a7-9569396bac09.png)
![rocket-chat-after](https://user-images.githubusercontent.com/2904679/76658617-8f73ad00-6585-11ea-9687-e5c46c560519.png)

![rc-2 17 9-before](https://user-images.githubusercontent.com/2904679/76658616-8f73ad00-6585-11ea-8c39-dce858a853bd.png)
![rc-2 17 9-after](https://user-images.githubusercontent.com/2904679/76658615-8e428000-6585-11ea-9931-613b531e99ca.png)

**Comment by mikemathewson** [comment]
The Check for Updates button makes a request to [latest.yml](https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.9/latest.yml) which results in a 404 error. The actual file is named [latest.yml-disabled.yml](https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.9/latest.yml-disabled.yml) for whatever reason.

**Comment by ketanvault** [comment]
Me too facing the same issue

**Comment by xmedeko** [comment]
The bug is still in 2.17.17, especially the problem that the resource is not translated, language English.

**Comment by foss-** [comment]
@xmedeko you mean 2.17.7? 2.17.9 is the current release. Can you try with that?
https://github.com/RocketChat/Rocket.Chat.Electron/releases
Update checks currently work fine for me using 2.17.9.

**Comment by xmedeko** [comment]
@foss- you are right, I have 2.17.7.

1. I had 2.17.9 and the update checks has not worked, even with the resource untranslated resource `dialog.about.errorWhileLookingForUpdates` bug.
2. So, I went to https://rocket.chat/install and there's a link to 2.17.7 ! I have not read the file name properly, installed it and posted my comment.
3. Now, installed again 2.17.9 from https://github.com/RocketChat/Rocket.Chat.Electron/releases and still have the update bug.

**Comment by pbros** [comment]
I have the same issue as well running 2.17.7 and 2.17.9.

**Comment by amathar** [comment]
Will this bug ever be fixed? 2.17.3 to 2.17.9 and no fix?

**Comment by avignat** [comment]
+1 seems that the dev' of the desktop client is dead

**Comment by foss-** [comment]
Update notice showed as expected for the update from 2.17.9 to 2.17.10, update downloaded and installed. Restart of RC client with no problem. Closing and thanks for addressing this problem.
For anybody stuck on previous releases: install 2.17.10 and you should no longer be seeing this problem:
https://github.com/RocketChat/Rocket.Chat.Electron/releases
![update fine](https://user-images.githubusercontent.com/5708172/87394537-3443dc80-c5b0-11ea-85e9-a01781a38a74.png)

**Comment by xmedeko** [comment]
@foss I see you have updated https://rocket.chat/install/ that's great. Just the Get it from Microsoft button links to https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.17.9/rocketchat-setup-2.17.9.exe i.e the previous version. Just make the link https://github.com/RocketChat/Rocket.Chat.Electron/releases/latest and github does redirect to the latest release.

**Comment by foss-** [comment]
I do not work for RocketChat nor have I done anything to their websites. But maybe a team member will pickup your suggestion which makes sense.
