### ISSUE TITLE
node 13.10.0+: Error: No "exports" main resolved

### ISSUE THREAD

**Issue by neurolabs** [RocketChat/Rocket.Chat.Electron#1616]
## My Setup

- Operating System: Gnu/Linux
- App Version: 2.17.9
- Installation type: git checkout, yarn start

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
When executing `yarn start` while using node 13.10.0 (or higher, including 14.3.0), the following error occurs:
```
src/main.js → app/main.js...
[!] (plugin babel) Error: No "exports" main resolved in /home/ole/projects/github/Rocket.Chat.Electron/node_modules/@babel/helper-compilation-targets/package.json
src/main.js
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ole/projects/github/Rocket.Chat.Electron/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ole/projects/github/Rocket.Chat.Electron/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```
With 13.9.0 it does not happen.

### Current Behavior
The application does not start.

### Expected Behavior
package.json names compatibility with node as `"node": ">=10.16.x"`, so I expext node 13.10.0+ to work.

**Comment by franckadil** [comment]
@neurolabs I fixed this issue by removing the `node_modules` directory and `package-lock.json` file then run `yarn `  to fresh install all packages then the issue was fixed.

**Comment by neurolabs** [comment]
@franckadil thanks, this worked for me as well.

**Comment by franckadil** [comment]
@neurolabs you're welcome! I was also struggling with it.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
