### ISSUE TITLE
Test Notifications don't work, other Notifications are rare

### ISSUE THREAD

**Issue by klou** [RocketChat/Rocket.Chat.Electron#1618]
## My Setup

- Operating System: Windows 10 1709 x64
- App Version: 2.17.9
- Installation type: exe, All Users

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

Rocket Chat installed on Ubuntu 18.04, from snap (2.x branch), with SSL.

## Description
I don't receive Desktop Notifications.  On a different 1703 fresh install of 2.17.9, I received from a message.  But from both installs (1703/1709) Test Notifications fail.

### Current Behavior
No visual behavior.  Attached message from Debug console: 

https://my.url.com/src/preload/notifications.js:77

```
Uncaught (in promise) TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-fetch\lib\index.js:1220:11)
    at C:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-fetch\lib\index.js:1293:21
    at new Promise (<anonymous>)
    at C:\Program Files\Rocket.Chat\resources\app.asar\node_modules\electron-fetch\lib\index.js:1290:29
(anonymous) @ remote.js:265
metaToPlainObject @ remote.js:265
error @ remote.js:219
metaToValue @ remote.js:225
(anonymous) @ remote.js:216
array @ remote.js:216
metaToValue @ remote.js:225
(anonymous) @ remote.js:286
(anonymous) @ remote.js:276
emit @ events.js:203
EventEmitter.emit @ domain.js:476
onMessage @ init.ts:50
async function (async)
create @ notifications.js:59
Notification @ notifications.js:52
(anonymous) @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:423
(anonymous) @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:105
notify @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:423
click .js-test-notifications @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:423
(anonymous) @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
e._withTemplateInstanceFunc @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
(anonymous) @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
(anonymous) @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
h._withCurrentView @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
(anonymous) @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
delegatedHandler @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:202
dispatch @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:55
g.handle @ 122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:55
```

### Expected Behavior
Test Message!

**Comment by klou** [comment]
Duplicates #1579

**Comment by klou** [comment]
I had a GPO **Turn off Toast notifications** that was blocking Windows notifications.
