### ISSUE TITLE
Error: Cannot find module 'tslib' / Failed to load module "appmenu-gtk-module" (Rocket.Chat 3.0.0-beta)

### ISSUE THREAD

**Issue by prigal** [RocketChat/Rocket.Chat.Electron#1708]
## My Setup

- Operating System: Ubuntu 20.04
- App Version: 3.0.0-beta
- Installation type:  Snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

I wanted to test the "beta" version of desktop.

```
➜  ~ sudo snap install rocketchat-desktop --beta
rocketchat-desktop (beta) 3.0.0-develop par Rocket.Chat (rocketchat✓) installé
➜  ~ rocketchat-desktop                                                  
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'tslib'
Require stack:
- /snap/rocketchat-desktop/180/resources/app.asar/app/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:919)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snap/rocketchat-desktop/180/resources/app.asar/app/main.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
Gtk-Message: 11:56:54.730: Failed to load module "appmenu-gtk-module"
```

I have installed : 

`➜  ~ sudo apt install --reinstall appmenu-gtk2-module appmenu-gtk3-module
`

But no luck. Maybe the real problem is 

`Error: Cannot find module 'tslib'
`

### Current Behavior

It doesn't start.

### Expected Behavior

It should start :)

**Comment by ankar84** [comment]
@tassoevan how to get beta version for Windows?

**Comment by tassoevan** [comment]
@prigal Thanks!
@ankar84 No option for it at the moment, just for the Snap Store.
