### ISSUE TITLE
rocketchat (3.0.0-1876) deb does not work on Xubuntu 18.04

### ISSUE THREAD

**Issue by zogith** [RocketChat/Rocket.Chat.Electron#1746]
## My Setup

- Operating System: Xubuntu 18.04 (with XFCE desktop)
- App Version: rocketchat_3.0.0_amd64.deb 3.0.0-1876
- Installation type:  deb file downloaded from github, installed with dpkg -i 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Error message produced on console, no GUI window appears.
Previous client (and before) works fine on this system, i.e. rocketchat_2.17.11_amd64.deb, reverting back to this version and all is good.

### Current Behavior
Following error appears on console when running with existing "./.config/Rocket.Chat" and no gui window shows, client nonfunctional:

```
rocketchat-desktop 
[bugsnag] Loaded!
xdg-settings: default-url-scheme-handler not implemented for xfce
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:1344:42
    at Generator.next (<anonymous>)
    at /opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:110:16)
    at setupServers (/opt/Rocket.Chat/resources/app.asar/app/main.js:1280:46)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:3225:11
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:111:62)
[bugsnag] Unhandled rejection…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:29:405)
    at applyRootWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:760:20)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:3241:5
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:111:62)

```
when running after renaming  "./.config/Rocket.Chat" a slightly different error appears, but the GUI window does not show still:

```
rocketchat-desktop 
[bugsnag] Loaded!
xdg-settings: default-url-scheme-handler not implemented for xfce
[bugsnag] Unhandled rejection…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:29:405)
    at applyRootWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:760:20)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:3241:5
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:111:62)


```

### Expected Behavior
No error message in terminal, rocketchat GUI window appears as per previous client versions.

**Comment by atemp** [comment]
same here using rpm version in CentOS 7 x86_64

**Comment by igeorgie** [comment]
Same problem on Ubuntu Desktop 20.04.1

**Comment by tomboe311** [comment]
same problem on Ubuntu 20.04.1 LTS with KDE

**Comment by rawahab** [comment]
Same type of error on windows
![Capture](https://user-images.githubusercontent.com/15166933/94784525-b8577480-03e7-11eb-8195-9a86291b4292.PNG)

**Comment by tassoevan** [comment]
Fixed?

**Comment by paulz1** [comment]
Seems that no...
I have the same problem on my Fedora. RocketChat client installed via Flatpak
```
Rocket.Chat                                          chat.rocket.RocketChat                  3.0.2      stable  system
```

**Comment by paulz1** [comment]
Updated today to 3.0.4 using flatpak and the bug has gone. Client works perfectly.

**Comment by tassoevan** [comment]
@zogith Any updates?

**Comment by zogith** [comment]
Hi @tassoevan

Sorry for the delay in responding.

I just tried rocketchat_3.0.7_amd64.deb and it works OK.. it did hang for me (didn't connect to server) until I selected "disable GPU" though, and produced more text errors on startup, but now works. After selecting "disable GPU" (which is now greyed out with no way to unselect) it runs without those text error messages being displayed.

I have an nvidia GPU with the nvida drivers loaded.

Initial error produced:


rocketchat-desktop 
[bugsnag] Loaded!
xdg-settings: default-url-scheme-handler not implemented for xfce
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:1358:42
    at Generator.next (<anonymous>)
    at /opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:110:16)
    at setupServers (/opt/Rocket.Chat/resources/app.asar/app/main.js:1319:46)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:3320:11
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:111:62)

.. but essentially rockechat client 3.0.7 is functioning for me so I would consider this bug resolved, thanks.

**Comment by Mephistophiles** [comment]
Rocketchat 3.3.0 - some problem:
```
[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Error processing argument at index 0, conversion failure from
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:29:405)
    at applyRootWindowState (/nix/store/31jlqar6r4s1jzdbd3dsxg90xmmlpf55-rocketchat-desktop-3.3.0/resources/app.asar/app/main.js:405:23)
    at BrowserWindow.<anonymous> (/nix/store/31jlqar6r4s1jzdbd3dsxg90xmmlpf55-rocketchat-desktop-3.3.0/resources/app.asar/app/main.js:573:13)
    at BrowserWindow.emit (events.js:310:20)
    at BrowserWindow.EventEmitter.emit (domain.js:482:12)
    at electron/js2c/browser_init.js:157:10844
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Rocket.Chat.Electron on  master [3…] via  v14.17.0
```

**Comment by prigaux** [comment]
I had the same issue today after a weird shutdown.

Investigation:
```
% grep -A1 bounds .config/Rocket.Chat/config.json 
		"bounds": {
			"x": -0,
```

By default in chromium, -0 is not a valid integer. `SetConvertNegativeZeroToInt` can be used to force a different chromium behaviour ([ref](https://codereview.chromium.org/2709103004)). 

What is the best solution for Rocket.Chat.Electron? Avoiding saving -0 to config.json? Using `SetConvertNegativeZeroToInt` (if it can be done) ?
