### ISSUE TITLE
[bug] Client crashes on incoming messages with 3.0.1

### ISSUE THREAD

**Issue by tomboe311** [RocketChat/Rocket.Chat.Electron#1760]
## My Setup

- Operating System: Ubuntu 20.04.1 LTS
- App Version: 3.0.1
- Installation type: snap

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

When I receive a message the client crashes. Only when I have the chat window open with the conversation partner

### Current Behavior

Client crashes and I have to restart it. No more process available

### Expected Behavior

No Crash

**Comment by atemp** [comment]
same here (3.0.2 CentOS 7.8.2003 x86_64

i get the following stack trace, maybe it is useful:
```
> /opt/Rocket.Chat/rocketchat-desktop 
[bugsnag] Loaded!
xdg-settings: unknown desktop environment
[bugsnag] Uncaught exception, the process will now terminate…
Error: Failed to serialize arguments
    at WebContents._.send (electron/js2c/browser_init.js:157:2252)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:59:25
    at Set.forEach (<anonymous>)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:58:19
    at Object.dispatch (/opt/Rocket.Chat/resources/app.asar/app/main.js:576:12)
    at dispatch (/opt/Rocket.Chat/resources/app.asar/app/main.js:583:16)
    at BrowserWindow.fetchAndDispatchWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:818:9)
    at BrowserWindow.emit (events.js:322:22)
    at BrowserWindow.EventEmitter.emit (domain.js:482:12)
    at BrowserWindow.topLevelDomainCallback (domain.js:137:15)
[bugsnag] Uncaught exception, the process will now terminate…
Error: Failed to serialize arguments
    at WebContents._.send (electron/js2c/browser_init.js:157:2252)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:59:25
    at Set.forEach (<anonymous>)
    at /opt/Rocket.Chat/resources/app.asar/app/main.js:58:19
    at Object.dispatch (/opt/Rocket.Chat/resources/app.asar/app/main.js:576:12)
    at dispatch (/opt/Rocket.Chat/resources/app.asar/app/main.js:583:16)
    at BrowserWindow.fetchAndDispatchWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:818:9)
    at BrowserWindow.emit (events.js:322:22)
    at BrowserWindow.EventEmitter.emit (domain.js:482:12)
    at BrowserWindow.topLevelDomainCallback (domain.js:137:15)
```

**Comment by atemp** [comment]
did not happen to me anymore since v3.0.3

**Comment by senpl** [comment]
Any progress on this. What could be done to fix it ??? Does no snap version also has this problem ???

**Comment by hosein-ghadiri** [comment]
Same here,

Operating System: Ubuntu 20.04.2 LTS
Version: 3.0.1
Installation type: snap

**Comment by amoebav** [comment]
I have this issue in v3.1.1 Windows client. It happens randomly maybe once every day or two. I don't have a rocket.chat window open, someone messages me, the message appears briefly and then it crashes. I have to start the client program again because it has completely closed out.

Client OS: Windows 10 x64 
Client RC: v3.1.1 
RC Server: v2.2.0

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
