### ISSUE TITLE
Rocket Chat Windows Client 3.2.3 not starting

### ISSUE THREAD

**Issue by mgfeal** [RocketChat/Rocket.Chat.Electron#2102]
Hi,

I was working with Windows 10 and Rocket Chat 3.2.3. I closed the app because changing between chats was very slow. And then Rocket Chat never start again.

If i start it from powershell:

[bugsnag] Loaded!
[bugsnag] Uncaught exception, the process will now terminateÔÇª
TypeError: Error processing argument at index 0, conversion failure from
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:29:405)
    at applyRootWindowState (C:\Program Files\Rocket.Chat\resources\app.asar\app\main.js:848:23)
    at BrowserWindow.<anonymous> (C:\Program Files\Rocket.Chat\resources\app.asar\app\main.js:1018:13)
    at BrowserWindow.emit (events.js:310:20)
    at BrowserWindow.EventEmitter.emit (domain.js:482:12)
    at electron/js2c/browser_init.js:157:10844
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Anyone with the same problem?
Thanks!

**Comment by ankar84** [comment]
@mgfeal can you try latest release 3.5.0?

**Comment by ankar84** [comment]
Can you test latest 3.5.3 release?

**Comment by prigaux** [comment]
It may be an issue similar to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1746 .

Suggestion : remove `bounds` from `config.json` (but I don't know where it is on Windows)

**Comment by stubb** [comment]
> Suggestion : remove `bounds` from `config.json` (but I don't know where it is on Windows)
That's it! The config file is located at  {userfolder}\AppData\Roaming\Rocket.Chat\config.json
