### ISSUE TITLE
[Linux] Client crashes when using "call" function with jitsi

### ISSUE THREAD

**Issue by roggy85** [RocketChat/Rocket.Chat.Electron#2226]
**Describe the bug**
When using the "Call" feature with jitsi, the welcome window openes fine but when clicking "Join meeting" the jitsi windows gets white and the RocketChat windows grey.
Closing the window with the jitsi call closes the whole RocketChat Client.

The App write this to the terminal when the app crashes:
```
[bugsnag] Uncaught exception, the process will now terminate…
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n._sendInternal (electron/js2c/browser_init.js:165:558)
    at Object.b._sendInternal (electron/js2c/browser_init.js:161:2550)
    at BrowserWindow.closedByUser (electron/js2c/browser_init.js:185:2450)
    at Object.onceWrapper (events.js:422:26)
    at BrowserWindow.emit (events.js:327:22)
    at BrowserWindow.EventEmitter.emit (domain.js:467:12)
```

What operating system and which version? RHEL 8.4
Which version of Rocket.Chat (Server)? 3.18.3
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.5.7
Is there any setting relevant changed? jitsi was updated to stable-6433

**To Reproduce**
1. Start a Call in the Rocket.Chat.Electron Client (jitsi) (for example with rocket.cat
2. Click on Join meeting
3. App crashes

**Expected behavior**
You join the call - with no app crash ;)

**Screenshots**
![screen1](https://user-images.githubusercontent.com/25770185/140886022-8cd4f457-e0af-42ed-9496-9a2696c1ddda.png)
![screen2](https://user-images.githubusercontent.com/25770185/140886067-5f918dae-7fc0-46a3-826e-e8561c100db7.png)

**Additional context**
The Rocket.Chat instance and Jitsi are running in podman containers.
Before the update to docker-jitsi-meet stable-6433 everything was running fine.
I know that was a change outside of Rocket.Chat or Rocket.Chat.Electron - but imho the app should not crash.
And only the Linux Version is affected - a test on the windows version worked fine.

**Comment by iFloris** [comment]
This also happens on MacOS 12.0.1 21A559 using Rocket.Chat `3.5.7` installed using Homebrew. 
On Mac the cause seems to be pretty clear:
```
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an com.apple.security.device.audio-input key with a string value explaining to the user how the app uses this data.
```
But perhaps something related to permissions is happening on Linux.

**Comment by ankar84** [comment]
related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1912

**Comment by roggy85** [comment]
Not sure if its really related...
digged a bit deeper - the application crashes with a signal 11 - segmentation violation...

```
           PID: 35114 (rocketchat-desk)
           UID: 1002 (xxx)
           GID: 1002 (xxx)
        Signal: 11 (SEGV)
     Timestamp: Tue 2021-11-16 08:50:02 CET (4min 28s ago)
  Command Line: /opt/Rocket.Chat/rocketchat-desktop --type=renderer --autoplay-policy=no-user-gesture-required --field-trial-handle=16296178035104316405,515268292889882005,131072 --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --disable-gpu-compositing --lang=en-US --app-path=/opt/Rocket.Chat/resources/app.asar --no-sandbox --no-zygote --disable-blink-features --node-integration-in-worker --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=9 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
    Executable: /opt/Rocket.Chat/rocketchat-desktop
 Control Group: /user.slice/user-1002.slice/session-8.scope
          Unit: session-8.scope
         Slice: user-1002.slice
       Session: 8
     Owner UID: 1002 (xxx)
       Boot ID: xxx
    Machine ID: xxx
      Hostname: pluto
       Storage: none
       Message: Process 35114 (rocketchat-desk) of user 1002 dumped core.
Coredump entry has no core attached (neither internally in the journal nor externally on disk).
```

but this started with an update of jitsi - rocketchat got no update... :/

**Comment by ankar84** [comment]
> related to #1912

Well, in that case, you are probably right!
There was one similar case in past, when update of Jitsi lead to RC.Electron crash

**Comment by ankar84** [comment]
@roggy85 can you try 3.6.0 version?
There was changes in UserAgent string which can potentially fix your issue.

**Comment by roggy85** [comment]
I gave it a try but after changing the setting to "open Video Chat using Application Window" the exact same behaviour is back and the app crashes with signal 11 - segmentation violation.

At least you can select if you want to have it open in a browser - which does not fix the issue itself but you don't kill the application each time you have a call ;)

**Comment by ankar84** [comment]
> At least you can select if you want to have it open in a browser - which does not fix the issue itself but you don't kill the application each time you have a call ;)

Yeah, it could be some kind of workaround for that issue. But proper fix is still needed.

**Comment by jeanfbrito** [comment]
In 3.6.0 the problem with OSX is to be resolved. 
I will try to find what is happening in linux, but I couldn't reproduce the bug yet.

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.

**Comment by roggy85** [comment]
The Call Window now works again! Thanks for the fix.

But at first I had to downgrade again to 3.6.0 because in 3.7.0 I can't open the Settings menu to switch back to open Call windows in Application.
Now in 3.7.0 The application crashes when I try to open any menu like
- Downloads
- Settings

And It looks like the "View -> Reload" does also not work anymore in 3.7.0.

I also tried to reset the whole App with no luck....

**Comment by klou** [comment]
Same 3.7.0 crashing behavior (Menu navigation), on Windows.

**Comment by shum16** [comment]
I'm experiencing the same problem now with a fresh installation:
RocketChat Server: 6.9.2
Jitsi Server: 2.0.9457
Ubuntu snap RocketChat Client: 3.9.14 (ubuntu 22.04)

The app crashes when joining the call:
![image](https://github.com/RocketChat/Rocket.Chat.Electron/assets/10737487/3f7b56f6-4bf8-47d5-8425-58eaae6a2f7e)
