### ISSUE TITLE
Rocket Chat Desktop crashes under Linux Mint

### ISSUE THREAD

**Issue by handmade-it** [RocketChat/Rocket.Chat.Electron#2244]
**Describe the bug**
Suddendly (probably after an update of some library) the Desktop app crashes with the following message:

[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:33:520)
    at applyRootWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:914:23)
    at BrowserWindow.<anonymous> (/opt/Rocket.Chat/resources/app.asar/app/main.js:1091:13)
    at BrowserWindow.emit (events.js:315:20)
    at BrowserWindow.EventEmitter.emit (domain.js:467:12)
    at electron/js2c/browser_init.js:161:12426
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

What operating system and which version?
- Linux Mint 20.1 "Ulyssa"
Which version of Rocket.Chat (Server)? 
- Unknown
Which version of Rocket.Chat.Electron (Electron/Desktop)?
- 3.6.0

**To Reproduce**
Simply launch the app

**Comment by jeanfbrito** [comment]
Please test if the lastest release (3.7.0) has solved this issue.

**Comment by handmade-it** [comment]
Hi, thank you for the quick reply. Unfortunatelly it still crashes.

This is the full output:

(rocketchat-desktop:4109438): Gtk-WARNING **: 23:22:32.728: Theme parsing error: gtk.css:9:0: Expected a valid selector
[4109470:1203/232233.011394:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[bugsnag] Loaded!
[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at applyRootWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:930:23)
    at BrowserWindow.<anonymous> (/opt/Rocket.Chat/resources/app.asar/app/main.js:1107:13)
    at BrowserWindow.emit (node:events:394:28)
    at BrowserWindow.emit (node:domain:475:12)
    at node:electron/js2c/browser_init:161:12770
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

Did Rocketchat save settings somewhere in the user's home directory? I tried to find and delete, in order to get Rocketchat to a full reset, but I couldn't find any settings  files.

**Comment by jeanfbrito** [comment]
We have the paths on readme.
On Linux, the full paths are:

/home/<username>/.config/Rocket.Chat/
/opt/Rocket.Chat/resources/

But I don't think that this will solve the issue. On another machines the issue don't happens?

**Comment by handmade-it** [comment]
Hi, thanks for the information.

I deleted the folder /home/.config/Rocket.Chat/ and now everything is working correctly.

**Comment by jeanfbrito** [comment]
Great news!

Em sáb, 4 de dez de 2021 16:27, handmade-it ***@***.***>
escreveu:
