### ISSUE TITLE
error at rocketchat-desktop startup

### ISSUE THREAD

**Issue by Rico29** [RocketChat/Rocket.Chat.Electron#2266]
**Describe the bug**

What operating system and which version? : CentOS Linux release 7.9.2009 (Core)
Which version of Rocket.Chat (Server)?  SNAP rocketchat-server  3.18.3    rev 1491
Which version of Rocket.Chat.Electron (Electron/Desktop)? rocketchat-3.7.1-1.x86_64 (updated today)
Is there any setting relevant changed?

**To Reproduce**
run rocketchat-desktop

[rico-desktop ]$ which rocketchat-desktop 
/usr/bin/rocketchat-desktop

[rico-desktop ]$ ll /usr/bin/rocketchat-desktop
lrwxrwxrwx 1 root root 35 22 déc.  13:17 /usr/bin/rocketchat-desktop -> /opt/Rocket.Chat/rocketchat-desktop

[rico-desktop ]$ LANG=C /usr/bin/rocketchat-desktop
[32472:1222/134732.234300:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: Interface « org.freedesktop.portal.FileChooser » non reconnue
[32472:1222/134732.234364:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
[32503:1222/134732.308117:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[bugsnag] Loaded!
[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at applyRootWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:930:23)
    at BrowserWindow.<anonymous> (/opt/Rocket.Chat/resources/app.asar/app/main.js:1107:13)
    at BrowserWindow.emit (node:events:394:28)
    at BrowserWindow.emit (node:domain:475:12)
    at node:electron/js2c/browser_init:161:12770
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

Regards,
Cédric

**Comment by jeanfbrito** [comment]
I have already found the problem and a fix will be added to the next release.
You can find your config.json and remove de bounds, probably the x is with (-0) value. Or just delete the config.json.

On Linux, the full paths are:

/home/<username>/.config/Rocket.Chat/
/opt/Rocket.Chat/resources/

**Comment by Rico29** [comment]
hello
~/.config/Rocket.Chat/config.json did the trick
Regards

**Comment by Rico29** [comment]
Hello,
I still have the same problem after upgrading to the latest release
