### ISSUE TITLE
Error: Render frame was disposed before WebFrameMain could be accessed

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat.Electron#2302]
**Describe the bug**
Can't scroll no more. This (image below) happens to me when I try to scroll. Maybe even without that, IDK.

What operating system and which version? Arch linux
Which version of Rocket.Chat (Server)? 3.18.x LTS
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.7.6-1
Is there any setting relevant changed? Upgrade from 3.7.1

**To Reproduce**
1. Open the app, try to open messages and scroll through them

**Expected behavior**
Working as before

**Screenshots**
![image](https://user-images.githubusercontent.com/11560794/151261887-229d7630-3419-4b5c-a0c4-e0cbe4b5b2c4.png)

**Additional context**
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
(node:5098) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 focus listeners added to [BrowserWindow]. Use emitter.setMaxListeners() to increase limit
(Use `electron --trace-warnings ...` to show where the warning was created)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at /usr/lib/rocketchat-desktop/app/main.js:63:17
    at new Promise (<anonymous>)
    at invoke (/usr/lib/rocketchat-desktop/app/main.js:51:51)
    at /usr/lib/rocketchat-desktop/app/main.js:101:13
    at Set.forEach (<anonymous>)
    at /usr/lib/rocketchat-desktop/app/main.js:100:19
    at /usr/lib/rocketchat-desktop/app/main.js:713:12
    at Object.dispatch (/usr/lib/rocketchat-desktop/node_modules/redux/lib/redux.js:667:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n._sendInternal (node:electron/js2c/browser_init:165:629)
    at Object.b._sendInternal (node:electron/js2c/browser_init:161:2571)
    at Object.onVisibilityChange (node:electron/js2c/browser_init:181:2947)
    at Object.emit (node:events:394:28)
    at Object.emit (node:domain:475:12)
    at BrowserWindow.visibilityChanged (node:electron/js2c/browser_init:33:836)
    at BrowserWindow.emit (node:events:406:35)
    at BrowserWindow.emit (node:domain:475:12)
    at BrowserWindow.<anonymous> (/usr/lib/rocketchat-desktop/app/main.js:1034:28)
    at BrowserWindow.emit (node:events:406:35)
^C^CSegmentation fault (core dumped)
```

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
