### ISSUE TITLE
[bugsnag] Event failed to send…

### ISSUE THREAD

**Issue by anfarr** [RocketChat/Rocket.Chat.Electron#2384]
**Describe the bug**
>Starting RC-client via menu does not work. In terminal error message is produced (see below).
>Client worked normally before. Unfortunately can't say when i used it last (sometime last week).

What operating system and which version?
>OS: Manjaro Linux x86_64
>DISTRIB_RELEASE=21.2.5
>Kernel: 5.10.105-1-MANJARO
>DE: Xfce 4.16
>WM: Xfwm4
Which version of Rocket.Chat.Electron (Electron/Desktop)?
>rocket-chat 3.8.0
and
>rocket-chat 3.8.2
Is there any setting relevant changed?
>Not that i know of. Switched kernel from linux510 -> linux515 but when swapping back error message persisted.

**To Reproduce**
1. Download release rocketchat-3.8.2-linux-x64.tar.gz or rocketchat-3.8.0-linux-x64.tar.gz
2. Extract tarball and run ./rocketchat-desktop
3. Receive error message featured below

**Expected behavior**
RC-desktop to start

**Error message**
when running rocket-chat 3.8.0 and 3.8.2 from terminal
```
[user@pc rocketchat-3.8.2-linux-x64]$ ./rocketchat-desktop 
[2898:0411/094006.446976:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[bugsnag] Loaded!
[bugsnag] Event failed to send…
Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 443
}
[bugsnag] Failed to send event to Bugsnag
[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at applyRootWindowState (/home/user/Packages/rocketchat-3.8.2-linux-x64/resources/app.asar/app/main.js:982:23)
    at BrowserWindow.<anonymous> (/home/user/Packages/rocketchat-3.8.2-linux-x64/resources/app.asar/app/main.js:1161:13)
    at BrowserWindow.emit (node:events:390:28)
    at BrowserWindow.emit (node:domain:475:12)
    at node:electron/js2c/browser_init:161:13121
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by jeanfbrito** [comment]
Do you are redirecting all the 443 requests on your machine?

**Comment by anfarr** [comment]
> Do you are redirecting all the 443 requests on your machine?

Not that i know of.
