### ISSUE TITLE
Object has been destroyed (is back)

### ISSUE THREAD

**Issue by kupe-dono** [RocketChat/Rocket.Chat.Electron#2388]
Hello Team,

Here is the return of a well known issue.

Steps to reproduce : 
- Install Rocket.Chat client 3.8.2 (amd64.deb version) > dpkg -i rocketchat (Install ok)
- Launch rocketchat client for the first time (OK)
- Close the window
- Relaunch rocketchat client (KO)
- If I want to make it works again, I have to reboot the laptop

Logs : 

```
Apr 12 08:54:11 0tacon systemd[2422]: Started Application launched by gnome-shell.
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]: (node:4632) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]:     at /opt/Rocket.Chat/resources/app.asar/app/main.js:2428:28
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]:     at Generator.next (<anonymous>)
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]:     at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:62)
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]: (node:4632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Apr 12 08:54:11 0tacon systemd[2422]: gnome-launched-rocketchat-desktop.desktop-8743.scope: Succeeded.
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]: [bugsnag] Unhandled rejection…
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]: TypeError: Object has been destroyed
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]:     at /opt/Rocket.Chat/resources/app.asar/app/main.js:2428:28
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]:     at Generator.next (<anonymous>)
Apr 12 08:54:11 0tacon rocketchat-desktop.desktop[4632]:     at fulfilled (/opt/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:62)
```

System config : 
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

Same results on Debian last version. (Parrot OS).

Thanks for your help and your great work !

**Comment by jeanfbrito** [comment]
I cant found it on bugsnag, did you desativated it? It has been solved some versions ago. Try enabling TrayIcon to see if stops happening.
