### ISSUE TITLE
Rocket.Chat won't start on Fedora Linux

### ISSUE THREAD

**Issue by vorons** [RocketChat/Rocket.Chat.Electron#2476]
**Describe the bug**
Rocket.Chat won't start. If run from a shortcut, nothing happens. Running from terminal gives the following:
```
rocketchat-desktop 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[7852:0820/114837.080563:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[bugsnag] Loaded!
[bugsnag] Uncaught exception, the process will now terminate…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (node:electron/js2c/browser_init:33:520)
    at applyRootWindowState (/opt/Rocket.Chat/resources/app.asar/app/main.js:1001:23)
    at BrowserWindow.<anonymous> (/opt/Rocket.Chat/resources/app.asar/app/main.js:1193:13)
    at BrowserWindow.emit (node:events:390:28)
    at BrowserWindow.emit (node:domain:475:12)
    at node:electron/js2c/browser_init:161:13146
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

OS: Fedora 36 x64 Wayland
Version of Rocket.Chat (Electron/Desktop): 3.8.7 RPM

**Comment by jeanfbrito** [comment]
@vorons this is a bug that will be fixed on the next release. For now, you can go to `/home/<username>/.config/Rocket.Chat/` and delete the `config.json` or edit it. There will be a `-1` number on the `rootWindowState` `bounds`, just change it to `0` (zero). It's a infinity number bug from chromium.

**Comment by vorons** [comment]
The value ```0``` is already set for ```rootWindowState``` ```bounds```. Deleting the file ```config.json``` is solved.
Thanks a lot.
