### ISSUE TITLE
Does not compile using NodeJs 7 on mac os

### ISSUE THREAD

**Issue by kakawait** [RocketChat/Rocket.Chat.Electron#252]
## My Setup

- **My OS name and version**: MacOsX 10.11.6
- **My current app version**: `develop` branch

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

```
git clone git@github.com:RocketChat/Rocket.Chat.Electron.git
cd Rocket.Chat.Electron
npm install
```
#### Current Behavior

```
> ffi@2.1.0 install /private/tmp/Rocket.Chat.Electron/app/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/private/tmp/Rocket.Chat.Electron/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
...
```
#### Expected Behavior

compile 👍

**Comment by xusai2014** [comment]
How to solve the problem
