### ISSUE TITLE
app crash with "electron.systemPreferences.getMediaAccessStatus is not a function" when clicking call button for jitsi call using "WebRTCPipeWireCapturer" to support desktop share on wayland

### ISSUE THREAD

**Issue by stylefish** [RocketChat/Rocket.Chat.Electron#2674]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Fedora 38

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.4

### Rocket.Chat Server Version

6.1.8

### Describe the bug

app chrashes when using the WebRTCPipeWireCapturer to support desktop shares when clicking on "start call" with jitsi provider.

this only happend when i'm using the WebRTCPipeWireCapturer, this is currently the only workaround to support desktop shares on wayland.

start command: 
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/rocketchat-desktop --file-forwarding chat.rocket.RocketChat @@u %U @@ --enable-features=WebRTCPipeWireCapturer`

console output:
```
[2:0602/113651.837232:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0602/113651.837325:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[50:0602/113651.895256:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
[bugsnag] Loaded!
[2:0602/113652.562151:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0602/113652.562187:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0602/113652.562207:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[bugsnag] 1 session(s) reported
Error occurred in handler for 'video-call-window/screen-recording-is-permission-granted': TypeError: electron.systemPreferences.getMediaAccessStatus is not a function
    at /app/Rocket.Chat/resources/app.asar/app/main.js:4794:55
    at Generator.next (<anonymous>)
    at /app/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:113:16)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:4793:84
    at /app/Rocket.Chat/resources/app.asar/app/main.js:438:58
    at node:electron/js2c/browser_init:2:97909
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81422)
    at EventEmitter.emit (node:events:513:28)
```

would be great if there is a solution or workaround to this because currently i'm downgrading rocket.chat electron to 3.8.13, which does support the pipewire capturer.

if you need more information i'm happy to help.

greetings

### How to Reproduce

- select a direct message chat 
- click on the "call" button 
- choose to start with microphone and video enabled
- click "start call".
=> app crashes

### Describe your Expected behavior

PipeWire capturer works with current rocket.chat electron version

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by stylefish** [comment]
fixed with 3.9.6, possibly due to #2701
