### ISSUE TITLE
Rocket.Chat 4.0.0 Desktop Client crashes on `rootWindow.addListener('close', ...)` when `isTrayIconEnabled === false && process.platform === 'linux'`

### ISSUE THREAD

**Issue by VeldoraTheDragon** [RocketChat/Rocket.Chat.Electron#2906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Arch Linux

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

4.0.0

### Rocket.Chat Server Version

6.7

### Describe the bug

When closing via `X`-Icon while the tray-icon has been disabled, the app crashes with the following message:
```
Uncaught Exception:
TypeError: Object has been destroyed
  at /opt/Rocket.Chat/resources/app.asar/app/main.js:2095:18
  at /opt/Rocket.Chat/resources/app.asar/app/main.js:2178:43
  at Array.forEach (<anonymous>)
  at App.<anonymous> (/opt/Rocket.Chat/resources/app.asar/app/main.js:2178:19)
  at App.emit (node:events:526:35)
  at App.emit (node:domain:488:12)
  at App.<anonymous> (/opt/Rocket.Chat/resources/app.asar/app/main.js:2432:18)
  at App.emit (node:events:526:35)
  at App.emit (node:domain:488:12)
```
Closing via `Ctrl + Q` or `File => Quit Rocket.Chat` doesn't trigger the error.

### How to Reproduce

1) Go to settings
2) disable `Tray Icon`
3) Close via `X`

### Describe your Expected behavior

The app should close like the other methods, without error.

### Anything else

I've unpacked the `app.asar` and opened the affected file on the described line.
It shows me the following line:
https://github.com/RocketChat/Rocket.Chat.Electron/blob/b4aeef45bdfb7b0b74375697543cc6c9c83ad866/src/ui/main/rootWindow.ts#L283

The other methods utilize `app.quit()` as seen in.
https://github.com/RocketChat/Rocket.Chat.Electron/blob/b4aeef45bdfb7b0b74375697543cc6c9c83ad866/src/ui/main/menuBar.ts#L111-L115

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by Vringe** [comment]
Same here with Arch and V4.0.1

**Comment by arpsyapathy** [comment]
Hello! Same here with Ubuntu 22.04 and 4.3.1
Any news?
@jeanfbrito

**Comment by cwrau** [comment]
Same thing happening here with v4.7.1, especially annoying if I just want to restart it

**Comment by jeanfbrito** [comment]
@cwrau its fixed on the latest version?

**Comment by cwrau** [comment]
> [@cwrau](https://github.com/cwrau) its fixed on the latest version?

Still happens to me with 4.8.1

**Comment by VeldoraTheDragon** [comment]
@jeanfbrito I've also updated to 4.8.1 and the issue still persists.
Can this issue be reopened and taken a look at again?

**Comment by jeanfbrito** [comment]
@VeldoraTheDragon can you test 4.9.0? If it happens yet, can you create a new issue? Then I will take a look on this. It was to be fixed. I need to find whats going on because I can have this issue on my tests.

**Comment by cwrau** [comment]
> [@VeldoraTheDragon](https://github.com/VeldoraTheDragon) can you test 4.9.0? If it happens yet, can you create a new issue? Then I will take a look on this. It was to be fixed. I need to find whats going on because I can have this issue on my tests.

This also still happens on 4.9.0 for me.

**Comment by Furret162** [comment]
I am using version 4.9.0 on Windows, and the issue can be reproduced with the following settings

Report errors to developers: OFF  
Tray Icon: OFF  
Minimize on close: OFF
