### ISSUE TITLE
Module version mismatch. Expected 50, got 51.

### ISSUE THREAD

**Issue by ihd2911** [RocketChat/Rocket.Chat.Electron#347]
I am facing error when i run npm start

Node 7.5.0
Npm 4.1.2
Ubuntu 14.04

App threw an error during load
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/lampp/htdocs/Rocket.Chat.Electron/node_modules/bindings/bindings.js:76:44)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/lampp/htdocs/Rocket.Chat.Electron/node_modules/bindings/bindings.js:76:44)

**Comment by alexbrazier** [comment]
I've had this error before. I think the solution was to either delete all the node_modules, or run `node-gyp rebuild`.

**Comment by ihd2911** [comment]
Deleted node_modules and installed again. Still not working
node-gyp rebuild is giving error 
gyp: binding.gyp not found (cwd: /opt/lampp/htdocs/Rocket.Chat.Electron) while trying to load binding.gyp


I was facing error 
Error: Module version mismatch. Expected 50, got 48 on node 6.9 
so i updated to latest node. now facing got 51.

**Comment by rodrigok** [comment]
Is your `npm install`giving errors?

The version mismatch throws when you are running the application and some compiled package with different nodejs versions. This happens when you compile the package (when installing) with a version and then update your nodejs and try to run the project.

**Comment by ihd2911** [comment]
No, npm Install is working properly. I am getting error only on start

**Comment by rodrigok** [comment]
Can you delete your `node_modules` folder, install it again, try to run and paste all the logs of this process here?

**Comment by ihd2911** [comment]
Nothing is in the log file if i run npm start

This is from the terminal
> rocketchat@2.4.0 start /opt/lampp/htdocs/Rocket.Chat.Electron
> gulp start

[15:10:32] Using gulpfile /opt/lampp/htdocs/Rocket.Chat.Electron/gulpfile.js
[15:10:32] Starting 'bundle'...
[15:10:32] Starting 'less'...
[15:10:32] Starting 'environment'...
[15:10:32] Finished 'environment' after 3.01 ms
[15:10:32] Starting 'watch'...
[15:10:32] Finished 'watch' after 15 ms
[15:10:32] Finished 'bundle' after 522 ms
[15:10:33] Finished 'less' after 900 ms
[15:10:33] Starting 'build'...
[15:10:33] Finished 'build' after 55 μs
[15:10:33] Starting 'start'...
[15:10:33] Finished 'start' after 13 ms
App threw an error during load
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/lampp/htdocs/Rocket.Chat.Electron/node_modules/bindings/bindings.js:76:44)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/lampp/htdocs/Rocket.Chat.Electron/node_modules/bindings/bindings.js:76:44)

**Comment by ihd2911** [comment]
Got it to working 

./node_modules/.bin/electron-rebuild --version=1.4.3
