### ISSUE TITLE
macOS Build - Tests okay, returns "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by krisgermann** [RocketChat/Rocket.Chat.Electron#439]
## My Setup

macOS Sierra (10.12.4 (16E195))
Build: master

- [ x ] I have tested with the latest application version
- [ x ] I can simulate the issue easily

#### Current Behavior

While "npm start" runs the program fine and I can test it out, works perfectly, and "npm test" as well as "npm test e2e" also runs with no errors, when it comes time to build (for macOS) and I run "npm run release', while it builds absolutely fine:

MacBook-Pro:Rocket.Chat.Electron-develop $ npm run release

> rocketchat-desktop@2.8.0-develop prerelease /Users/kris/Desktop/App/Rocket.Chat.Electron-develop
> gulp build --env=production

[09:06:09] Using gulpfile ~/Desktop/Rocket.Chat.Electron-develop/gulpfile.js
[09:06:09] Starting 'bundle'...
[09:06:09] Starting 'less'...
[09:06:09] Starting 'environment'...
[09:06:09] Finished 'environment' after 4.07 ms
[09:06:10] Finished 'bundle' after 385 ms
[09:06:10] Finished 'less' after 623 ms
[09:06:10] Starting 'build'...
[09:06:10] Finished 'build' after 36 μs

When I start the application, I get this error:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot find module 'debug'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/user/Desktop/App/Rocket.Chat.Electron-develop/dist/mac/Chat.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _load_debug (/Users/user/Desktop/App/Rocket.Chat.Electron-develop/dist/mac/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/electronHttpExecutor.js:17:45)
    at Object.<anonymous> (/Users/user/Desktop/App/Rocket.Chat.Electron-develop/dist/mac/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:11:15)
    at Object.<anonymous> (/Users/user/Desktop/App/Rocket.Chat.Electron-develop/dist/mac/Chat.app/Contents/Resources/app.asar/node_modules/electron-updater/out/electronHttpExecutor.js:104:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

#### Expected Behavior

I expect the app to run with no issue

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.
