### ISSUE TITLE
failed to rebuild rocket.chat.2.9.0,it seems that connect ETIMEDOUT 23.23.139.60:443

### ISSUE THREAD

**Issue by zcgecho** [RocketChat/Rocket.Chat.Electron#543]
electron-builder 19.20.1
Rebuilding native production dependencies for win32:x64
Rebuilding native dependency spellchecker
Error: E:\nodejs\node.exe exited with code 1
Output:
yarn run v1.0.2
$ node-gyp rebuild

G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\spellchecker>if not defined npm_config_node_gyp (node "E:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.5.0 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.6/iojs-v1.7.6.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 23.23.139.60:443
gyp ERR! stack     at Object._errnoException (util.js:1026:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1049:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\spellchecker
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder-util\src\util.ts:155:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
From previous event:
    at spawn (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder-util\src\util.ts:118:3)
    at default.map.concurrency (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\src\util\yarn.ts:152:7)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\src\util\yarn.ts:150:27
From previous event:
    at rebuild (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\out\util\yarn.js:96:22)
    at G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\src\util\yarn.ts:21:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at installOrRebuild (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\out\util\yarn.js:34:21)
    at G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\src\cli\install-app-deps.ts:58:42
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\out\cli\install-app-deps.js:52:21)
    at loadEnv.then (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\out\cli\cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\out\cli\cli.js:155:68)
    at Object.self.runCommand (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (G:\zhangrui\Rocket.Chat.Electron-2.9.0\node_modules\electron-builder\out\cli\cli.js:151:465)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by gdelavald** [comment]
Hey @zcgecho, sorry to not be able to help you more. This seems like an issue with your machine or npm, please look for similar problems in StackOverflow and how to resolve them.
