### ISSUE TITLE
fs.js:997 Uncaught Error: ENOTDIR: not a directory, readlink '/Users/xzns/Documents/code/electron/electron/spec/fixtures/asar/a.asar/dir1/link1'

### ISSUE THREAD

**Issue by francescoyang** [RocketChat/Rocket.Chat.Electron#565]
Uncaught Error: ENOTDIR: not a directory, readlink '/Users/xzns/Documents/code/electron/electron/spec/fixtures/asar/a.asar/dir1/link1'
    at Object.fs.readlinkSync (fs.js:997:18)
    at addExtraFieldsSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/inspect.js:82:30)
    at Object.inspectSync [as sync] (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/inspect.js:107:3)
    at walkSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:15:24)
    at list.sync.forEach (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:24:7)
    at Array.forEach (native)
    at walkSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:23:21)
    at list.sync.forEach (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:24:7)
    at Array.forEach (native)
    at walkSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:23:21)

Help

**Comment by francescoyang** [comment]
[
<img width="1329" alt="wx20171017-115916 2x" src="https://user-images.githubusercontent.com/3077018/31646410-5a636ed4-b2c7-11e7-8173-d81f5d9cda2a.png">
](url)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
