### ISSUE TITLE
yarn check --integrity always failed

### ISSUE THREAD

**Issue by SilverRainZ** [RocketChat/Rocket.Chat.Electron#588]
## My Setup
- Operating System: Arch Linux latest
- App Version: 2.9.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

Whild i build rocket chat with with archlinux's `extra-x86_64-build` ([PKGBUILD](https://aur.archlinux.org/packages/rocketchat-desktop/)), `yarn check --integrity` always failed.

```
yarn check v1.3.2
verbose 0.41 Checking for configuration file "/build/rocketchat-desktop/src/Rocket.Chat.Electron-2.9.0/.npmrc".
verbose 0.411 Checking for configuration file "/build/.npmrc".
verbose 0.411 Checking for configuration file "/usr/etc/npmrc".
verbose 0.411 Checking for configuration file "/build/rocketchat-desktop/src/Rocket.Chat.Electron-2.9.0/.npmrc".
verbose 0.411 Checking for configuration file "/build/rocketchat-desktop/src/.npmrc".
verbose 0.411 Checking for configuration file "/build/rocketchat-desktop/.npmrc".
verbose 0.412 Checking for configuration file "/build/.npmrc".
verbose 0.412 Checking for configuration file "/build/rocketchat-desktop/src/Rocket.Chat.Electron-2.9.0/.yarnrc".
verbose 0.412 Checking for configuration file "/build/.yarnrc".
verbose 0.413 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.413 Checking for configuration file "/build/rocketchat-desktop/src/Rocket.Chat.Electron-2.9.0/.yarnrc".
verbose 0.413 Checking for configuration file "/build/rocketchat-desktop/src/.yarnrc".
verbose 0.413 Checking for configuration file "/build/rocketchat-desktop/.yarnrc".
verbose 0.413 Checking for configuration file "/build/.yarnrc".
verbose 0.415 current time: 2017-11-05T02:59:21.864Z
error Couldn't find an integrity file
verbose 0.478 Error: Found 1 errors.
    at /usr/lib/node_modules/yarn/lib/cli.js:57476:13
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:92:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:103:13
    at <anonymous>
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```
### Expected Behavior

`yarn check --integrity` should returns 0 to let build process continue.

**Comment by gdelavald** [comment]
Hey @SilverRainZ, I couldn't reproduce this on my local (osx) but I'll test it on some VMs.
Can you add reproducing steps (from checkout to yarn commands executed)? Thanks a lot.

**Comment by alexbrazier** [comment]
This appears to be an issue with yarn https://github.com/yarnpkg/yarn/issues/3167, and not the Rocket.Chat app.

**Comment by SilverRainZ** [comment]
Thanks for your replies.

@gdelavald I build it on Arch Linux with devtools' `extra-x86_64-build`, it may can not bee reproduced on macOS.
