### ISSUE TITLE
Error executing windows client

### ISSUE THREAD

**Issue by manuelmsoria** [RocketChat/Rocket.Chat.Electron#640]
## My Setup
- Operating System: Windows 10 Home. Version 10.0.16299 compilation 16299.
- App Version: 2.9.0

- I have tested with the latest version
- I can simulate the issue easily

## Description
If I try to start windows electron client y seems to show splash screen and it's closed inmediatly. If started to happen after last Windows update.
If I try to execute it from console an explicit error is shown (see attached image).

![screenshot](https://user-images.githubusercontent.com/31923003/34196807-010faf80-e564-11e7-8f5a-3375de08e298.png)

**Comment by Nopony** [comment]
Experiencing same issue on Win10 Enterprise build 15063

```Error: Error: Cannot find module 'electron-is-dev'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (H:\Applications\rocketchat\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at _load_electronIsDev (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:41:52)
    at H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:329:35
    at Generator.next (<anonymous>)
    at NsisUpdater.loadUpdateConfig (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:371:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:84:43)
    at Lazy.get value [as value] (H:\Applications\rocketchat\resources\app.asar\node_modules\lazy-val\out\main.js:17:27)    at H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:239:33
From previous event:
    at NsisUpdater.loadUpdateConfig (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:371:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:84:43)
    at Lazy.get value [as value] (H:\Applications\rocketchat\resources\app.asar\node_modules\lazy-val\out\main.js:17:27)    at H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:239:33
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:329:11)
    at H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:222:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:282:11)
    at NsisUpdater.checkForUpdates (H:\Applications\rocketchat\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:166:35)
    at checkForUpdates (H:\Applications\rocketchat\resources\app.asar\app\background.js:391:37)
    at afterMainWindow (H:\Applications\rocketchat\resources\app.asar\app\background.js:516:5)
    at App.<anonymous> (H:\Applications\rocketchat\resources\app.asar\app\background.js:606:5)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)```

**Comment by manuelmsoria** [comment]
Reinstalling it as global app (for all users) it works perfectly.

**Comment by gdelavald** [comment]
Thanks for the workaround @manuelmsoria, we are looking into a fix for this for the next release.
