### ISSUE TITLE
Cannot start RocketChat client on debian: failed to map segment from shared object

### ISSUE THREAD

**Issue by er0k** [RocketChat/Rocket.Chat.Electron#676]
## My Setup
- Operating System: Linux Debian
- App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Description:

```
$ uname -a
Linux eth 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux
```
I just downloaded and installed 2.10.5, but I get this error when trying to run rocketchat:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.gJ5bk6: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/opt/Rocket.Chat+/resources/app.asar/node_modules/@paulcbetts/system-idle-time/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/Rocket.Chat+/resources/app.asar/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
```
### Steps to Reproduce:

1. run `rocketchat`

### Expected behavior:

rocketchat client should start

### Actual behavior:

rocketchat client does not start

**Comment by er0k** [comment]
This is caused by my tmp partition being mounted as `noexec` (as recommended by the [Securing Debian Manual](https://www.debian.org/doc/manuals/securing-debian-howto/ch4.en.html#s4.10))

```
er0k@eth:~ 
$ grep tmp /etc/fstab
tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0
er0k@eth:~ 
$ mount | grep \/tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime,size=524288k)
```

As a workaround I can re-mount /tmp as executable:

```
sudo mount -o remount,exec /tmp
```

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.
