### ISSUE TITLE
Update check does not work

### ISSUE THREAD

**Issue by alfredbez** [RocketChat/Rocket.Chat.Electron#747]
## My Setup
- Ubuntu 18.04
- App Version: 2.11.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
![peek 2018-06-11 10-31](https://user-images.githubusercontent.com/1001186/41220743-9b84ac2e-6d62-11e8-83fb-bf1e5b81d06b.gif)
1. Open Rocket.Chat client via terminal (`$ rocketchat`)
1. Open "About" window (in Menu "Rocket.Chat+" > "About Rocket.Chat+")
1. Click on "Check for Updates"
1. Animated Icon is spinning forever and you see the following error in the terminal:
```
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Rocket.Chat+/resources/app-update.yml'
    at /opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:391:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:555:7)
    at Lazy.AppUpdater.configOnDisk (/opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:134:43)
    at Lazy.get value [as value] (/opt/Rocket.Chat+/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:298:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/opt/Rocket.Chat+/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at checkForUpdates (/opt/Rocket.Chat+/resources/app.asar/app/background.js:389:37)
    at afterMainWindow (/opt/Rocket.Chat+/resources/app.asar/app/background.js:512:5)
    at App.<anonymous> (/opt/Rocket.Chat+/resources/app.asar/app/background.js:597:5)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
```

### Current Behavior
An error occurs, but the user is not informed about this and thinks, that the update check still runs.

### Expected Behavior
* Tell the user, that something goes wrong
* Make the update check work again

**Comment by dzienisz** [comment]
this is serious error, many user will never update after this version :( they will need to manually update the app :/
