### ISSUE TITLE
rocket chat electron 2.14.1 not workibg right click on mouse in windows 7

### ISSUE THREAD

**Issue by evant89** [RocketChat/Rocket.Chat.Electron#956]
rocket chat electron 2.14.1 not workibg right click on mouse in windows 7

When I click the right mouse button in the program - nothing happens. The menu does not appear

**Comment by tassoevan** [comment]
@evant89 Is some error message appearing when click `Window > Toggle DevTools > Console`?

**Comment by evant89** [comment]
> @evant89 Is some error message appearing when click `Window > Toggle DevTools > Console`?

webview.js:73 webview: Unable to load preload script: C:\Program Files\Rocket.Chat\resources\app.asar\app\public\preload.js
webview.js:73 webview: Error: ENOENT, dictionaries not found in C:\Program Files\Rocket.Chat\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:108:19)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:616:9)
    at SpellCheck.getDictionariesFromInstallDirectory (C:\Program Files\Rocket.Chat\resources\app.asar\app\public\lib\SpellCheck.js:200:25)
    at SpellCheck.loadAvailableDictionaries (C:\Program Files\Rocket.Chat\resources\app.asar\app\public\lib\SpellCheck.js:164:9)
    at new SpellCheck (C:\Program Files\Rocket.Chat\resources\app.asar\app\public\lib\SpellCheck.js:51:8)
    at Object.<anonymous> (C:\Program Files\Rocket.Chat\resources\app.asar\app\public\preload.js:122:22)
    at Object.<anonymous> (C:\Program Files\Rocket.Chat\resources\app.asar\app\public\preload.js:125:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
webview.js:73 webview: Loading:
webview.js:73 webview: Mixed Content: The page at 'https://open.rocket.chat/channel/support' was loaded over HTTPS, but requested an insecure image 'http://s3.amazonaws.com/info-mongodb-com/_com_assets/cms/mongodb-for-giant-ideas-bbab5c3cf8.png'. This content should also be served over HTTPS.
webview.js:73 webview: Error getting your geolocation
webview.js:73 webview: Error getting your geolocation
webview.js:73 webview: No live audio input: [object NavigatorUserMediaError]
webview.js:73 webview: No live audio input: [object NavigatorUserMediaError]
webview.js:73 webview: No live audio input: [object NavigatorUserMediaError]

**Comment by evant89** [comment]
![2018-10-29 16-34-37](https://user-images.githubusercontent.com/36101287/47656819-8eacc780-db98-11e8-8fb0-4ac8f9e24321.png)

**Comment by evant89** [comment]
End on ubuntu 18.04
![2018-10-29 16-38-58](https://user-images.githubusercontent.com/36101287/47657151-332f0980-db99-11e8-8638-f0f14ac0d60f.png)

**Comment by tassoevan** [comment]
Thank you very much.
