### ISSUE TITLE
Doesn't build from source with newer node version.

### ISSUE THREAD

**Issue by ml-** [RocketChat/Rocket.Chat.Electron#957]
## My Setup
- Operating System: ArchLinux
- App Version: master https://github.com/RocketChat/Rocket.Chat.Electron/commit/2a0723bf5b27ae91b07a6dc974d87441e464eff3
- Installation type: Build from source

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Rocket.Chat.Electron doesn't build on systems with latest stable node version.

```
$ node --version
v11.0.0

$ yarn --version
1.10.1
```

### Current Behavior

```
$ yarn build release:linux
yarn run v1.10.1
$ gulp build-app release:linux
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/ml/apps/Rocket.Chat.Electron/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/home/ml/apps/Rocket.Chat.Electron/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/ml/apps/Rocket.Chat.Electron/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Expected Behavior

`yarn build release:linux` (or any release:*) to build successfully.

### Workaround

For now, a workaround is to ignore the `yarn.lock` file by installing the node modules with
`yarn install --no-lockfile`

Would be nice if someone with more knowledge could have a look at this and update the lockfile to work with latest node. Thank you.

**Comment by tassoevan** [comment]
Seems related to https://github.com/zurb/foundation-sites/issues/11555. I'll look at it.

**Comment by ml-** [comment]
As mentioned here: https://github.com/gulpjs/gulp/issues/2246#issuecomment-434638127

`yarn upgrade` solves the problem and the project can build again.

But is this the the correct way to do that?

**Comment by ml-** [comment]
Hello @tassoevan,

I just tried this: https://github.com/gulpjs/gulp/issues/2246#issuecomment-435646661
And it seems to solve the issue.

This commit solved it:
https://github.com/addaleax/natives/commit/0abbec6b0e211c6bbe3bf0d2b33fcd68f5a6c980

**Comment by tassoevan** [comment]
Hmm, I've tried to update `natives`, but not to that version. Let me check it.
